import "./globals.css";
import { Inter, Audiowide, Bruno_Ace } from "next/font/google";

const audiowide = Audiowide({
  weight: "400",
  style: "normal",

  preload: false,
});
const bruno = Bruno_Ace({
  weight: "400",
  style: "normal",
  preload: false,
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={bruno.className}>{children}</body>
    </html>
  );
}
